USE netflix;


CREATE TABLE movies (
idMovies INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
title VARCHAR(45) NOT NULL,
genre VARCHAR(45) NOT NULL,
image VARCHAR(1000) NOT NULL,
category VARCHAR(45) NOT NULL,
year INT 
);


CREATE TABLE user (
idUser INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
user VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
name VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
plan_details VARCHAR(45) NOT NULL
);


CREATE TABLE actors (
idActor INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(45) NOT NULL,
lastname VARCHAR(45) NOT NULL,
country VARCHAR(45) NOT NULL,
birthday DATE
);